config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'members#index'
  resources :members, only: %i[index show create]
  get '/members/:id/search/:query', to: 'members#search'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/connection.rb
# frozen_string_literal: true

class Connection < ApplicationRecord
  belongs_to :member
  belongs_to :friend, class_name: 'Member'
  after_create :mutual_association

  private

  def mutual_association
    Connection.find_or_create_by!(member_id: friend_id, friend_id: member_id)
  end
end

app/models/member.rb
# frozen_string_literal: true

class Member < ApplicationRecord
  has_many :tags
  has_many :connections, class_name: 'Connection', foreign_key: 'friend_id'

  after_create :get_meta_data

  def friends
    friend_ids = *connections.map(&:member_id) || []
    !friend_ids.empty? ? Member.find(friend_ids) : []
  end

  # search stuff

  def keyword_search(word)
    tags.map(&:text).grep(/#{word.downcase}/i)
  end

  def friends_with_common(word)
    @member_has_common_terms = []
    friends.each do |member|
      if member.keyword_search(word).count > 0
        @member_has_common_terms << member
      end
    end
    @member_has_common_terms
  end

  def bread_crumbs_from(word)
    found_paths = []
    friends.each do |middleman|
      (middleman.friends_with_common(word) - [self] - friends).each do |friend|
        bc_payload = {
          liason_chain: [self, middleman, friend],
          heading_matches: friend.keyword_search(word)
        }
        found_paths << bc_payload
      end
    end
    found_paths
  end

  private

  def get_meta_data
    populate_tags
    populate_short_url
  end

  def populate_tags
    Util.scrape_tags(self)
  end

  def populate_short_url
    update_attributes(short_url: Shorty.shorten(original_url))
  end
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  belongs_to :member
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/members_controller.rb
# frozen_string_literal: true

class MembersController < ApplicationController
  def index
    @members = Member.all
  end

  def create
    name = params[:member][:name]
    url = params[:member][:original_url]
    @member = Member.create(name: name, original_url: url)

    # link selected friends
    params[:member][:friends].compact.map(&:to_i).each do |id|
      @member.connections.create(member_id: id)
    end

    respond_to do |format|
      format.html { redirect_to @member, notice: 'Member was successfully created.' }
    end
  end

  def show
    @member = Member.find(params[:id])
  end

  def search
    member = Member.find(params[:id])
    render json: member.bread_crumbs_from(params[:query])
  end

  # not in spec
  def update
    Member.find(params[:id]).update_attributes(params[:member])
  end

  def delete
    @member = Member.find(params[:id]).destroy
  end

  private

  def member_params
    params.require(:member).permit(:name, :original_url)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/members_helper.rb
# frozen_string_literal: true

module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <style>
    body {
      margin-left: 5%;
      font-size: 11pt;
      font-family: Arial,Helvetica Neue,Helvetica,sans-serif;

    }
    ul.tags, ul.friend_links {
        -moz-column-count: 3;
        -moz-column-gap: 20px;
        -webkit-column-count: 3;
        -webkit-column-gap: 20px;
        column-count: 3;
        column-gap: 20px;
    }

    div#search {
      float: right; width:50%; height: 50%; margin-top: 7%;
    }
  </style>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: Member.new, local: true) do |f| %>
  Name: <%= f.text_field :name %><br />
  Url : <%= f.text_field :original_url %><br />
	Friends: <%= f.select(:friends, Member.all.map {|p| [ p.name, p.id ] }, 
                                           { :prompt => "Please select"}, 
                                           { :multiple => true, :size => 5 }) %> <br />

  <%= f.submit %>
<% end %>

app/views/members/index.html.erb
<style>
	body {
		margin-left: 5%;
	}
</style>

<h1> Listing Members </h1>
<table>
  <thead>
    <th> Name </th>
    <th> Website </th>
    <th> Friends </th>
  </thead>
  <tbody>
  <% @members.each do |member| %>
    <tr>
      <td>
        <%= link_to member.name, member_path(member) %>
      </td>
      <td>
        <%= link_to member.short_url, member.short_url%>
      </td>
      <td>
        <%= member.friends.count %>
      </td>
    </tr>
  <%end %>
  </tbody>
</table>

<%= render partial: 'form' %>

app/views/members/show.html.erb
 
<%= link_to 'Back', root_path %>

<style>
</style>

<div id="search">
	<input id="query" placeholder="search" value="" />
	<div id="results"> </div>
</div>

<dl>  
  <dt> Name: </dt>       
  <dd> <h1><%= @member.name %> </h1></dd>
  <dt> ShortUrl: </dt>
  <dd>
    <%= link_to @member.short_url,  @member.short_url %>
  </dd>
  <dt>
     Website:    
  </dt>
  <dd>
    <%= link_to @member.original_url, @member.original_url %>
  </dd>
  <dt>
    Friends:    
  </dt>
  <dd>
    <%= @member.friends.count %>
  </dt>
  <dt>
 Headings:
  </dt>
  <dd>
    <ul class="tags">
      <% @member.tags.each do |tag| %>
        <li> <%= tag.text %> </li>
      <% end %>
    </ul>
  </dd>
  <dt>
 Friend's:
  </dt>
  <dd>
    <ul class="friend_links">
      <% @member.friends.each do |friend| %>
        <li> <%= link_to friend.name, member_path(friend)%> 
        </li>
      <% end %>
    </ul>
  </dd>
</dl>


<script>

	var XHR = {};
	XHR.base = function(callback) {
		var request = new XMLHttpRequest(), callback = callback || function () {};
		request.onreadystatechange = function() {
			if (this.readyState == 4 ) {
				callback(request.response);
			}
		};
		return request;
	}
	XHR.get = function (url, params, callback) { 
		var request = XHR.base(callback);
		request.open("GET",[url, '?', params].join(''), /*async flag -> */ true); 
		request.send();
	}

	function get_page_id() {
		let tokens = location.pathname.split(/\//) 
		return tokens[tokens.length - 1]
	}

	function link(member) {
	   return `<a href="/members/${member.id}">${member.name}</a>`;	
  }

  document.getElementById('query').addEventListener('change', function() {
    XHR.get(`/members/${ get_page_id() }/search/${this.value}`, '', (raw_json) => {
      markup = JSON.parse(raw_json).map((result) => {
        breadcrumb =  result.liason_chain.map((member) => {
          return link(member);
        }).join(' &rarr; ')
        matching_tags_found = result.heading_matches.join('</li><li>')
        ul = `<ul>${ '<li>' + matching_tags_found + '</li>'}</ul>`;
        return breadcrumb + ul
      }).join('<br />');
      document.getElementById('results').innerHTML = markup;
    })
  });

</script>